### ISSUE TITLE
System-RW on Samsung Galaxy S23 Ultra achieved by lebigmac

### ISSUE THREAD

**Issue by lebigmac1** [mohammad92/unpack-kernel-tools#1]
<img src="https://systemrw.com/img/Samsung_Galaxy_S23_FULL_RW_by_lebigmac_WWW.SYSTEMRW.COM.jpg">

Hello Afaneh92. How are you doing? You don't have to waste your precious time anymore on trying to make the System RW on the Samsung Galaxy S23 Ultra. I have achieved it already. It was very easy to adapt my original **System-RW / SuperRW featuring MakeRW / ro2rw by lebigmac** script to make it work with this new next-gen Samsung device ;) Why Samsung stopped using the F2FS ?

There is only 1 big problem. Phone boots perfect with your TWRP and is FULL-RW according to screenshot above but it refuse to boot into Android. Do you have any idea why? I already patched <code>/vendor/etc/*fstab*</code> to be bootable with ext4. Maybe I need permissive kernel? What do you think? Thank you for your advice! I know you are Samsung expert. I am coming from a Xiaomi background myself ;)

By the way what's your email? Do you have personal homepage?
Your TWRP works perfect. Everything is mountable and even /data is decrypted. I was amazed when I saw there is fastboot mode on Samsung device inside your TWRP. I couldn't believe it! Great job!
Keep up the good work.

**Comment by lebigmac1** [comment]
Hi afaneh sorry to burst your bubble but you can stop trying to take my low hanging System-RW fruit now. I am the creator of System-RW and not afaneh or dr-ketan. Also please forward this message to your friend dr-ketan.
Please acknolwedge that that I am creator of System-RW just like I acknowledge that you did wonderful job with your TWRP and your permissive kernel is just AMAZING <3

Thank you and looking forward to making a flashable System-RW zip for your custom recovery if you are interested ;)
See you soon! You can always contact me at lebigmac1@protonmail.com
Looking forward to hearing from you soon ;)

<img src="https://www.systemrw.com/img/Samsung_galaxy_s23_system-rw_teaser_lebigmac_WWW.SYSTEMRW.COMteaser.jpg">

**Comment by mohammad92** [comment]
Thanks, but wrong repo and subject.
